import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/">HOME</Link>
          <Link href="/product">PRODUCT</Link>
          <Link href="/board">BOARD</Link>
          <div className="m_r">
            <Link href="/">Login</Link>
            <Link href="/">About</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
